server:
  port: 9999
spring:
  application:
    name: spring-security-demo
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/ai_tools_img?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      database: 2
mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
knife4j:
  enable: true
  setting:
    language: zh_cn
    swagger-model-name: 实体类列表
minio:
  accessKey: minioadmin
  secretKey: 2002101mama520
  bucket: omni-agent
  dir: chat
  endpoint: http://110.42.210.113:9000

logging:
  file:
    path: ./logs
  level:
    root: info
    com.geshu.pts: info
    org.springframework: warn
